version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
      - 5672:5672

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - CHUNKSIZE=25
      - FILE_COMMETS=comments.csv
      - FILE_POSTS=posts.csv
      - COMMETS_QUEUE=comments_queue 
      - POSTS_QUEUE=posts_queue

  comments_filter_body:
    container_name: comments_filter_body
    image: comments_filter_body:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=comments_queue
      - QUEUE_SEND=comments_filter_queue

  comments_filter_student:
    container_name: comments_filter_student
    image: comments_filter_student:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=comments_filter_queue
      - QUEUE_SEND=student_ids_queue

  comments_groupby_postid:
    container_name: comments_groupby_postid
    image: comments_groupby_postid:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=comments_filter_queue
      - QUEUE_SEND=comments_groupby_queue

  posts_avg_sentiment:
    container_name: posts_avg_sentiment
    image: posts_avg_sentiment:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=comments_groupby_queue
      - QUEUE_SEND=post_sentiments_queue

  posts_max_avg_sentiment:
    container_name: posts_max_avg_sentiment
    image: posts_max_avg_sentiment:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=post_sentiments_queue
      - QUEUE_SEND=post_avg_sentiments_queue

  posts_filter_columns:
    container_name: posts_filter_columns
    image: posts_filter_columns:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_queue
      - QUEUE_SEND=posts_filter_queue

  posts_sum_score:
    container_name: posts_sum_score
    image: posts_sum_score:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_filter_queue
      - QUEUE_SEND=posts_score_queue

  posts_avg_score:
    container_name: posts_avg_score
    image: posts_avg_score:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - QUEUE_RECV=posts_score_queue
      - QUEUE_SEND=posts_avg_queue
